service:
  name: Quiz

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

functions:
  next:
    handler: handler.next
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-nextjs-plugin